apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-true
  labels:
    app: nginx-privilege-true
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true
